export type ProcessComponentCatalogItem = {
  id: string;
  name: string;
  category: string;
  zone: string;
  location: string;
  nearbyLabels: string[];
  instanceCount: number;
  status: "pending" | "wip" | "done";
  viewBox: string;
  notes?: string;
};

/** Urutan build 01..N — nomor di UI mengikuti index array ini. */
export const PROCESS_COMPONENT_CATALOG: ProcessComponentCatalogItem[] = [
  {
    id: "sensor-tag-box",
    name: "SensorTagBox",
    category: "Data Readout",
    zone: "Kiri — Generator",
    location: "Kotak sensor TE/PT di sisi generator.",
    nearbyLabels: ["TE-0057 · 153.8 °F"],
    instanceCount: 10,
    status: "done",
    viewBox: "0 0 80 44",
    notes: "Reuse untuk semua TE/PT (generator, coupling, atas). Tag dinamis via SensorTagBoxBound.",
  },
  {
    id: "vertical-motor",
    name: "VerticalMotor",
    category: "Motor / Fan",
    zone: "Bawah kiri, coupling, turbine",
    location: "Silinder vertikal dengan status RUN (merah) / STOP (hijau).",
    nearbyLabels: ["MOT 0109 · STOP"],
    instanceCount: 6,
    status: "done",
    viewBox: "0 0 48 88",
    notes: "Label bawah dinamis dari registry. Klik toggle RUN/STOP. Tag: MOT_0108A_RUN, dll.",
  },
  {
    id: "horizontal-motor",
    name: "HorizontalMotor",
    category: "Motor / Fan",
    zone: "Tengah — Shaft coupling",
    location: "Motor horizontal di shaft, label MOT + kode di kanan, STOP/RUN di bawah body.",
    nearbyLabels: ["MOT-0129 · STOP"],
    instanceCount: 1,
    status: "done",
    viewBox: "0 0 76 36",
    notes: "Tag dinamis MOT_0129_RUN. Klik toggle RUN/STOP.",
  },
  {
    id: "solenoid-valve",
    name: "SolenoidValve",
    category: "Valve",
    zone: "Atas — Gas Fuel",
    location: "Valve bow-tie + badge S, label OPN/CLS.",
    nearbyLabels: ["OPN · S · horizontal"],
    instanceCount: 8,
    status: "done",
    viewBox: "0 0 56 46",
    notes: "Dinamis: horizontal/vertical, actuator S/M, flow arrow, OPN/CLS. Klik toggle.",
  },
  {
    id: "vane-value-box",
    name: "VaneValueBox",
    category: "Data Readout",
    zone: "Kanan — Turbine",
    location: "Kotak nilai VIGV / VBV / VSV di depan casing turbine.",
    nearbyLabels: ["VIGV · 29.0"],
    instanceCount: 3,
    status: "done",
    viewBox: "0 0 72 36",
    notes: "Label di atas, nilai hijau tanpa unit. Tag: VIGV, VBV, VSV.",
  },
  {
    id: "demand-feedback-box",
    name: "DemandFeedbackBox",
    category: "Data Readout",
    zone: "Atas — Gas Fuel / FCV",
    location: "Kotak abu kecil DMD / FB % di dekat valve.",
    nearbyLabels: ["DMD 18.4%"],
    instanceCount: 4,
    status: "pending",
    viewBox: "0 0 72 40",
  },
  {
    id: "electrical-panel",
    name: "ElectricalPanel",
    category: "Data Readout",
    zone: "Kiri — Generator (inset)",
    location: "Panel data listrik di dalam body generator.",
    nearbyLabels: ["11.8 KV"],
    instanceCount: 1,
    status: "pending",
    viewBox: "0 0 120 100",
  },
  {
    id: "fan-box",
    name: "FanBox",
    category: "Motor / Fan",
    zone: "Atas kiri & atas kanan",
    location: "Housing fan A+B dengan label MOT di atas.",
    nearbyLabels: ["MOT-4103 · A merah RUN"],
    instanceCount: 2,
    status: "pending",
    viewBox: "0 0 140 90",
    notes: "Fan A spin merah, Fan B statis hijau.",
  },
  {
    id: "fan-down-link",
    name: "FanDownLink",
    category: "Motor / Fan",
    zone: "Atas — fan ke generator",
    location: "Garis hijau vertikal + panah dari fan box.",
    nearbyLabels: ["panah hijau ↓"],
    instanceCount: 2,
    status: "pending",
    viewBox: "0 0 24 80",
  },
  {
    id: "circular-pump",
    name: "CircularPump",
    category: "Motor / Fan",
    zone: "Bawah — Sprint Water",
    location: "Pompa bundar hijau di jalur SPRINT WTR SUPPLY.",
    nearbyLabels: ["MOT-2100 · STOP"],
    instanceCount: 1,
    status: "pending",
    viewBox: "0 0 56 56",
  },
  {
    id: "circuit-breaker",
    name: "CircuitBreaker",
    category: "Electrical Symbol",
    zone: "Atas — Generator",
    location: "Simbol breaker horizontal 52G / 52U.",
    nearbyLabels: ["52G"],
    instanceCount: 2,
    status: "pending",
    viewBox: "0 0 64 24",
  },
  {
    id: "generator-assembly",
    name: "GeneratorAssembly",
    category: "Major Equipment",
    zone: "Kiri — Generator",
    location: "Blok hijau besar + nose stepped + inset panel.",
    nearbyLabels: ["11.8 KV · generator body"],
    instanceCount: 1,
    status: "pending",
    viewBox: "0 0 280 120",
    notes: "Compose body + ElectricalPanel.",
  },
  {
    id: "shaft-coupling",
    name: "ShaftCoupling",
    category: "Major Equipment",
    zone: "Tengah — Shaft",
    location: "Shaft biru horizontal + housing coupling abu.",
    nearbyLabels: ["TE-0079 · coupling"],
    instanceCount: 1,
    status: "pending",
    viewBox: "0 0 200 80",
  },
  {
    id: "turbine-assembly",
    name: "TurbineAssembly",
    category: "Major Equipment",
    zone: "Kanan — Turbine",
    location: "Casing turbine multi-stage + cone kanan.",
    nearbyLabels: ["VIGV · turbine casing"],
    instanceCount: 1,
    status: "pending",
    viewBox: "0 0 320 160",
  },
  {
    id: "combustion-flame",
    name: "CombustionFlame",
    category: "Major Equipment",
    zone: "Tengah — Turbine combustor",
    location: "Ikon api kecil orange di combustion section.",
    nearbyLabels: ["flame icon"],
    instanceCount: 3,
    status: "pending",
    viewBox: "0 0 24 24",
  },
  {
    id: "motorized-valve",
    name: "MotorizedValve",
    category: "Valve",
    zone: "Gas Fuel / Water",
    location: "Valve bow-tie + badge M.",
    nearbyLabels: ["M · CLS"],
    instanceCount: 3,
    status: "pending",
    viewBox: "0 0 40 52",
  },
  {
    id: "control-valve",
    name: "ControlValve",
    category: "Valve",
    zone: "Bawah — NOX Water",
    location: "FCV-2019 + DemandFeedbackBox.",
    nearbyLabels: ["FCV-2019"],
    instanceCount: 1,
    status: "pending",
    viewBox: "0 0 80 64",
    notes: "Compose MotorizedValve + DemandFeedbackBox.",
  },
  {
    id: "supply-inlet",
    name: "SupplyInlet",
    category: "Label / Inlet",
    zone: "Atas & bawah",
    location: "Label supply + panah masuk pipa.",
    nearbyLabels: ["GAS FUEL"],
    instanceCount: 3,
    status: "pending",
    viewBox: "0 0 160 32",
  },
  {
    id: "process-diagram-svg",
    name: "ProcessDiagramSvg",
    category: "Root Composer",
    zone: "Seluruh canvas",
    location: "Root SVG compose semua komponen.",
    nearbyLabels: ["1422 × 814 px"],
    instanceCount: 1,
    status: "pending",
    viewBox: "0 0 1422 814",
    notes: "Ganti <img> di main screen setelah semua komponen lulus evaluasi.",
  },
];

export function catalogNumber(index: number) {
  return String(index + 1).padStart(2, "0");
}

export const CATALOG_SUMMARY = {
  templateCount: PROCESS_COMPONENT_CATALOG.length,
  instanceCount: PROCESS_COMPONENT_CATALOG.reduce((sum, item) => sum + item.instanceCount, 0),
  doneCount: PROCESS_COMPONENT_CATALOG.filter((item) => item.status === "done").length,
  referenceImage: "/hmi/process-diagram.png",
  referenceSize: "1422 × 814 px",
};
